from app.modules.clinical_orders.entities import (
    ClinicalServiceGroup,
    ClinicalServiceInput,
    FastingPolicy,
    RoomServiceType,
    SchedulingPriority,
)

CLINICAL_SERVICE_SEEDS = (
    ClinicalServiceInput(
        code="LAB-HEMA",
        name="Huyết học",
        service_group=ClinicalServiceGroup.LABORATORY,
        room_service_type=RoomServiceType.BLOOD_TEST,
        description="Tổng phân tích tế bào máu",
        execution_minutes_min=3,
        execution_minutes_max=5,
        turnaround_minutes_min=45,
        turnaround_minutes_max=60,
        fasting_policy=FastingPolicy.NOT_REQUIRED,
        fasting_hours_min=None,
        fasting_hours_max=None,
        scheduling_priority=SchedulingPriority.FLOW_START,
        notes="Luôn ưu tiên đưa lên đầu luồng để kích hoạt đồng hồ chạy TAT.",
        room_locations=("101 K1", "102 K1", "103 K1"),
    ),
    ClinicalServiceInput(
        code="LAB-BIOCHEM",
        name="Sinh hóa máu cơ bản",
        service_group=ClinicalServiceGroup.LABORATORY,
        room_service_type=RoomServiceType.BLOOD_TEST,
        description="Glucose, ure, creatinine, men gan",
        execution_minutes_min=3,
        execution_minutes_max=5,
        turnaround_minutes_min=60,
        turnaround_minutes_max=90,
        fasting_policy=FastingPolicy.REQUIRED,
        fasting_hours_min=6,
        fasting_hours_max=10,
        scheduling_priority=SchedulingPriority.MORNING,
        notes="Xếp làm buổi sáng sớm. Chỉ được ăn sau khi đã lấy mẫu.",
        room_locations=("101 K1", "102 K1", "103 K1"),
    ),
    ClinicalServiceInput(
        code="LAB-IMMUNO",
        name="Miễn dịch / Nội tiết",
        service_group=ClinicalServiceGroup.LABORATORY,
        room_service_type=RoomServiceType.BLOOD_TEST,
        description="Hormone, tuyến giáp, dấu ấn ung thư",
        execution_minutes_min=3,
        execution_minutes_max=5,
        turnaround_minutes_min=90,
        turnaround_minutes_max=120,
        fasting_policy=FastingPolicy.CONDITIONAL,
        fasting_hours_min=None,
        fasting_hours_max=None,
        scheduling_priority=SchedulingPriority.LONG_TURNAROUND,
        notes="Ưu tiên sớm vì đây là nhóm có thời gian đợi kết quả lâu nhất.",
        room_locations=("101 K1", "102 K1", "103 K1"),
    ),
    ClinicalServiceInput(
        code="LAB-URINE",
        name="Tổng phân tích nước tiểu",
        service_group=ClinicalServiceGroup.LABORATORY,
        room_service_type=RoomServiceType.URINE_TEST,
        description="Bệnh nhân tự lấy bệnh phẩm",
        execution_minutes_min=10,
        execution_minutes_max=10,
        turnaround_minutes_min=30,
        turnaround_minutes_max=45,
        fasting_policy=FastingPolicy.NOT_REQUIRED,
        fasting_hours_min=None,
        fasting_hours_max=None,
        scheduling_priority=SchedulingPriority.FLEXIBLE,
        notes="Có thể lồng ghép trong lúc đi vệ sinh hoặc chờ các phòng khác.",
        room_locations=("107 K1", "108 K1"),
    ),
)
